.TH "AdvanceMENU Frontend" 1
.SH NAME
advmenu \- AdvanceMENU Frontend
.SH SYNOPSIS 
advmenu [\-default] [\-remove] [\-cfg FILE]
.PD 0
.PP
.PD
	[\-log] [\-version] [\-help]
.PD 0
.PP
.PD
.SH DESCRIPTION 
AdvanceMENU is a front\-end to run the AdvanceMAME, AdvanceMESS,
MAME, MESS, Raine and other emulators.
.PP
Simply run it in the same directory of the emulator and press
\`f1\' to get the help screen or \`~\' for the main menu.
.PP
Press \`tab\' to change the display mode. Press \`space\' to change
the preview mode.
.PP
To run a game press \`enter\'. Press \`esc\' to exit.
.PP
The major features are:
.PD 0
.IP \(bu
Simply download and run. Copy the executable and run it!
.IP \(bu
Auto update of the rom info.
.IP \(bu
Vertical and horizontal orientation.
.IP \(bu
Support for any TV/Arcade Monitor like AdvanceMAME but it\'s
good also for a normal PC monitor.
.IP \(bu
Static and Animated image and clip preview (PNG/PCX/ICO/MNG).
Up to 192 images at the same time!
.IP \(bu
Sound preview. (MP3/WAV). You can select a special sound for
every game played when the cursor move on it.
.IP \(bu
Sound backgrounds (MP3/WAV). Play your favorite songs or
radio records in background.
.IP \(bu
Sound effects (MP3/WAV) for key press, program start, game
start, program exit...
.IP \(bu
Support for zipped images and sounds archives.
.IP \(bu
Screen\-saver. A slide show of the game images.
.IP \(bu
Selectable background and help images with translucency.
.PD
.SH OPTIONS 
.TP
.B \-default
Add to the configuration file all the missing options
with default values.
.TP
.B \-remove
Remove from the configuration file all the options
with default values.
.TP
.B \-cfg FILE
Select an alternate configuration file. In Linux and Mac
OS X the you can prefix the file name with \[dq]./\[dq] to
load it from the current directory.
.TP
.B \-log
Create the file \`advmenu.log\' with a lot of internal
information. Very useful for bug report.
.TP
.B \-verbose
Print some startup information.
.TP
.B \-version
Print the version number, the low\-level device drivers
supported and the configuration directories.
.TP
.B \-help
Print a short command line help.
.PP
In Linux and Mac OS X you can also use \`\-\-\' before options instead of \`\-\'.
In DOS and Windows you can also use \`/\'.
.SH EMULATORS 
The program supports many type of emulators. The emulators
AdvanceMAME, AdvanceMESS, MAME, SDLMAME, DMAME,
DMESS and DRAINE are directly supported and the only thing
you should do is to run the AdvanceMENU program in the same
directory of the emulator.
.PP
All the other emulators are supported with the emulator
type \`generic\'.
.SS generic \- Generic emulator 
For the \`generic\' emulator no additional rom information is
needed. Only the name and the size of the rom files are used.
.PP
You should specify all emulator information and directories
with the \`emulator\' and \`emulator_*\' options in the
\`advmenu.rc\' file.
.PP
You need to use at least the \`emulator\' and \`emulator_roms\'
options to inform AdvanceMENU how to run the emulator and where
to find the roms.
.PP
For example:
.PP
.RS 4
emulator \[dq]snes9x\[dq] generic \[dq]c:\\game\\snes9x\\snes9x.exe\[dq] \[dq]%f\[dq]
.PD 0
.PP
.PD
emulator_roms \[dq]snes9x\[dq] \[dq]c:\\game\\snes9x\\roms\[dq]
.PD 0
.PP
.PD
emulator_roms_filter \[dq]snes9x\[dq] \[dq]*.smc;*.sfc;*.fig;*.1\[dq]
.PD 0
.PP
.PD
.RE
.PP
.RS 4
emulator \[dq]zsnes\[dq] generic \[dq]c:\\game\\zsnes\\zsnes.exe\[dq] \[dq]\-e \-m roms\\%f\[dq]
.PD 0
.PP
.PD
emulator_roms \[dq]zsnes\[dq] \[dq]c:\\game\\zsnes\\roms\[dq]
.PD 0
.PP
.PD
emulator_roms_filter \[dq]zsnes\[dq] \[dq]*.smc;*.sfc;*.fig;*.1\[dq]
.PD 0
.PP
.PD
.RE
.PP
The various %s, %f, %p, ... macros are explained in the \`emulator\'
option description.
.PP
The roms are searched in the path specified with the
\`emulator_roms\' option in the \`advmenu.rc\' file. For every file
found (with any extension) a game is added in the menu.
You can filter the files with the \`emulator_roms_filter\' option.
.PP
All the snapshots are searched in the directories specified with
the \`emulator_*\' options using the same name of the rom file.
.PP
If you want, you can manually write a MAME like information file
and name it as \`ENUNAME.lst\'. This file has the same format
of the output of the \`\-listinfo\' MAME command.
Actually only the information \`game\', \`name\', \`description\', \`year\',
\`manufacturer\', \`cloneof\' are used.
Please note that this file is used only to add information at the
existing games. The games present in this file are not automatically
added at the game list.
.SS advmame \- AdvanceMAME 
For the \`advmame\' emulator type the roms informations are
gathered from the file \`ENUNAME.xml\'. If this file doesn\'t
exist, it\'s created automatically with emulator \`\-listxml\'
command.
.PP
The directories specified in the \`dir_rom\' option in the
\`advmame.rc\' file are used to detect the list of the
available roms. In the DOS and Windows versions of the
program the \`advmenu.rc\' file is searched in the same directory
of the emulator. In the Unix version it\'s searched in the
\`HOME/.advance\' directory.
.PP
The directory specified in \`dir_snap\' is used to
detect the list of available snapshots.
.SS advmess \- AdvanceMESS 
For the \`advmess\' emulator the rom information is gathered
from the file \`EMUNAME.xml\'. If this file doesn\'t exist,
it\'s created automatically with emulator \`\-listxml\' command.
.PP
The directories specified in the \`dir_rom\' option in the
\`advmess.rc\' file are used to detect the list of the
available bioses.
.PP
All the directories listed in the option \`dir_image\' are
read and all the files found in the \`machine\' directories
are inserted as software if the extension is recognized as a
valid device extension for the current \`machine\' or if it\'s a
\`zip\' file.
For example if the \`dir_image\' options is \`c:\\software\',
AdvanceMENU scans the directories \`c:\\software\\ti99_4a\',
\`c:\\software\\sms\', \`c:\\software\\gameboy\'...
Files in the main directory \`c:\\software\' are NOT checked.
.PP
When you select to run a zip file, the zip file is opened and
all the files in the zip with a valid name and with a recognized
device extension are added at the AdvanceMESS command line.
A file is considered to have a valid name if has the same name
of the zip of if it has the name of the zip with an additional
char. For example in the file \`alpiner.zip\' the files
\`alpiner.bin\', \`alpinerc.bin\' and \`alpinerg.bin\' have a valid
name. This feature can be used to group all the required roms
to play a software in a single zip file.
.PP
The file extension is also used to correctly select the device
type when calling AdvanceMESS.
.PP
The directory specified in \`dir_snap\' is used to detect the
list of available snapshots.
At any exit of AdvanceMESS if a new snapshot is created, this
file is moved to the correct \`snap\\system\' directory renaming
it as the software started.
For example, suppose that you run the \`ti99_4a\' system with the
software \`alpiner\'. If you press F12 during the emulation, the
file \`snap\\ti99_4a.png\' is created. When you return to
AdvanceMENU the file is moved automatically to
\`snap\\ti99_4a\\alpiner.png\'.
.SS mame \- Windows MAME 
For the \`mame\' emulator the roms information is gathered from
the file \`EMUNAME.xml\'. If this file doesn\'t exist, it\'s created
automatically with emulator \`\-listxml\' command.
.PP
The directories specified in the \`rompath\' option in the
\`mame.ini\' file are used to detect the list of the available
roms.
.PP
The directory specified in \`snapshot_directory\' is
used to detect the list of available snapshots.
.SS sdlmame \- SDL MAME 
For the \`sdlmame\' emulator the roms informations are gathered
from the file \`EMUNAME.xml\'. If this file doesn\'t exist, it\'s
created automatically with emulator \`\-listxml\' command.
.PP
The directories specified in the \`rompath\' option in the
\`HOME/.mame/mame.ini\' file in Linux and Mac OS X and in the \'mame.ini\'
file in Windows are used to detect the list of the available roms.
.PP
Please note that in Linux and Mac OS X the \'mame.ini\' file doesn\'t
support relative paths for roms and other files. Always use absolute
paths configuring SDL MAME. You can use the \[dq]$HOME\[dq] variable to
refers at the Linux/Mac OS X user home directory.
.PP
The directory specified in \`snapshot_directory\' is used to detect the
list of available snapshots files.
.SS dmame \- DOS MAME 
For the \`dmame\' emulator the roms informations are gathered
from the file \`EMUNAME.xml\'. If this file doesn\'t exist, it\'s
created automatically with emulator \`\-listxml\' command.
.PP
The directories specified in the \`rompath\' option in the
\`mame.cfg\' file are used to detect the list of the available
roms.
.PP
The directory specified in \`snap\' is used to
detect the list of available snapshots.
.SS dmess \- DOS MESS 
For the \`dmess\' emulator the roms informations are gathered
from the file \`EMUNAME.xml\'. If this file doesn\'t exist, it\'s
created automatically with emulator \`\-listxml\' command.
.PP
The directories specified in the \`biospath\' option in the
\`mess.cfg\' file are used to detect the list of the available
bioses.
.PP
All the directories listed in the option \`softwarepath\' are
read and all the \`zip\' files found in the \`subsystem\'
directories are inserted as software.
For example if the \`softwarepath\' options is \`c:\\software\',
AdvanceMENU scans the directories \`c:\\software\\ti99_4a\',
\`c:\\software\\sms\', \`c:\\software\\gameboy\'...
Zips in the main directory \`c:\\software\' are NOT checked.
.PP
When you select one of these entries the zip is opened and is
searched the first file with the same name of the zip but
different extension. This file is used as the argument of the
\`\-cart\' option when running \`mess\'.
AdvanceMENU is NOT able to use other supports like \`\-flop\'.
.PP
All the aliases present if the \`mess.cfg\' are inserted as
software entries. When you select one of these entries the
\`mess\' option \`\-alias\' is used to start the game.
.PP
You can set an arbitrary description on an alias specification
adding it on the same line of the alias after the comment char
\'#\' using this format:
.PP
.RS 4
ALIAS = ALIAS_DEF # Description | YEAR | MANUFACTURER
.PD 0
.PP
.PD
.RE
.PP
For example:
.PP
.RS 4
[ti99_4a]
.PD 0
.PP
.PD
ti\-inva = \-cart ti\-invac.bin \-cart ti\-invag.bin \\
.PD 0
.PP
.PD
	# Invaders | 1982 | Texas Instrument
.PD 0
.PP
.PD
.RE
.PP
At any exit of the emulator if a new snapshot is created, this file
is moved to the correct \`snap\\system\' directory renaming it as
the software started.
For example, suppose that you run the \`ti99_4a\' system with the
software \`alpiner\'. If you press F12 during the emulation, the
file \`snap\\ti99_4a.png\' is created. When you return to
AdvanceMENU the file is moved automatically to
\`snap\\ti99_4a\\alpiner.png\'.
.SS draine \- DOS Raine 
For the \`draine\' emulator the roms informations are gathered
from the file \`EMUNAME.lst\'. If this file doesn\'t exist, it\'s
created automatically with emulator \`\-gameinfo\' command.
.PP
All the directories specified in the \`rom_dir_*\' options are
used to detect the list of the available roms.
.PP
The directory specified in \`screenshots\' is used to detect the
list of available snapshots.
.SH CONFIGURATION 
The file \`advmenu.rc\' is used to save the current state of the
front\-end. It\'s read at startup and saved at exit. You can
prevent the automatic save at the exit with the \`config\' option.
.PP
In DOS and Windows the configuration options are read from the
file \`advmenu.rc\' in the current directory.
.PP
In Linux and Mac OS X the configuration options are read from the
files \`advmame.rc\' and \`advmess.rc\' in the $host, $data and
the $home directory.
The $host directory is \`$SYSCONFDIR\', where $SYSCONFDIR is the
\`sysconfdir\' directory configured with the \`configure\' script.
The default is \`/usr/local/etc\'.
The $data directory is \`$DATADIR/advance\', where $DATADIR is the
\`datadir\' directory configured with the \`configure\' script.
The default is \`/usr/local/share\'.
The $home directory is \`$ADVANCE\', where $ADVANCE is the value of the
ADVANCE environment variable when the program is run.
If the ADVANCE environment variable is missing the $home directory
is \`$HOME/.advance\' where $HOME is the value of the HOME environment
variable.
If both the ADVANCE and HOME environment variables are missing the
$data directory became also the $home directory.
.PP
The priority of the options is in the order: $host, $home and $data.
.PP
The $home directory is also used to write all the information
by the program. The files in the $host and $data directory are only read.
.PP
You can include an additional configuration files with the \`include\'
option. In DOS and Windows the files are searched in the current directory.
In Linux and Mac OS X the files are searched in the $home directory if
they are expressed as a relative path. You can force the search in the
current directory prefixing the file with \`./\'.
To include more than one file you must divide the names with \`;\' in
DOS and Windows, and with \`:\' in Linux and Mac OS X.
.PP
You can force the creation of a default configuration file with the
command line option \`\-default\'.
.PP
In DOS and Windows the directory name separator is \`\\\' and the
multi\-directory separator is \`;\'. In Linux and Mac OS X the directory
name separator is \`/\' and the multi\-directory separator is \`:\'.
.SS Global Configuration Options 
This section describes the global options used to
customize the the program.
.PP
A subset of the configuration options are saved per
emulator basis to allow different configurations for
different emulators. Please note that these specific emulator
configurations are not activated if you select to show
more than one emulator at time.
In this case only the default configuration is used.
Specifically these special options are \`mode\', \`sort\',
\`preview\', \`group_include\' and \`type_include\'.
.SS config 
Selects if and when the configuration modified by the user at
runtime should be saved.
.PP
config save_at_exit | restore_at_exit | restore_at_idle
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I save_at_exit
Save any changes before exiting
(default).
.HP 4
.I restore_at_exit
Don\'t save the changes. At the next
run, restore the previous configuration.
.HP 4
.I restore_at_idle
Restore the previous configuration
after the \`idle\' time.
.PD
.RE
.PP
You can manually save the configuration at runtime from the
main menu.
.SS emulator 
Selects the emulators to list in the menu. You can specify more than
one emulator.
.PP
WARNING! Before playing with this option, you should do a
backup copy of your current \`advmenu.rc\' because when you remove
an emulator, the game information for that emulator (like
the time played) is lost.
.PP
emulator \[dq]EMULATOR\[dq] (generic | advmame | advmess | mame | dmame
.PD 0
.PP
.PD
	| dmess | draine) \[dq][\-]EXECUTABLE\[dq] \[dq]ARGUMENTS\[dq]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR
The name for the emulator. It must be
different for every emulator defined.
.HP 4
.I generic
It\'s a generic emulator.
.HP 4
.I advmame
It\'s the AdvanceMAME emulator.
.HP 4
.I advmess
It\'s the AdvanceMESS emulator.
.HP 4
.I mame
It\'s the Window MAME emulator.
.HP 4
.I dmame
It\'s the DOS MAME emulator.
.HP 4
.I dmess
It\'s the DOS MESS emulator.
.HP 4
.I draine
It\'s the DOS Raine emulator.
.HP 4
.I [\-]EXECUTABLE
The executable path of the emulator.
In DOS and Windows you can also use a batch (.bat)
file, but this prevent the automatic generation of
the listing file which must be generated manually.
You can put a \`\-\' in front of the file path
to ignore any error returned by the executable.
.HP 4
.I ARGUMENTS
The arguments to be passed to the emulator.
The arguments are required only for the \`generic\'
emulator. For the others, AdvanceMENU automatically
adds the required arguments to run a
game. However, you may wish to add extra
arguments.
.PD
.RE
.PP
In the emulator arguments some macros are substituted
with some special values:
.RS 4
.PD 0
.HP 4
.I %s
Expanded as the game name. For example \[dq]pacman\[dq].
.HP 4
.I %p
Expanded as the complete path of the rom. For
example \[dq]c:\\emu\\roms\\pacman.zip\[dq].
.HP 4
.I %f
Expanded as the rom name with the extension. For
example \[dq]pacman.zip\[dq].
.HP 4
.I %o[R0,R90,R180,R270]
Expanded as one of the R* string,
depending on the current menu orientation.
Note that you cannot use space in the R* string.
For example \[dq]%o[,\-ror,\-flipx,\-rol] %o[,,\-flipy,]\[dq]
correctly rotate the AdvanceMAME emulator.
.PD
.RE
.PP
For the \`generic\' emulator type you need use the % macros
to tell at the emulator which game run. For all the other emulator
types this information is automatically added by AdvanceMENU.
.PP
Examples for DOS and Windows:
.PP
.RS 4
emulator \[dq]AdvanceMAME\[dq] advmame \[dq]advmame\\advmame.exe\[dq] \\
.PD 0
.PP
.PD
	\[dq]%o[,\-ror,\-flipx,\-rol] %o[,,\-flipy,]\[dq]
.PD 0
.PP
.PD
emulator \[dq]MAME\[dq] mame \[dq]mame\\mame.exe\[dq] \[dq]\-nohws\[dq]
.PD 0
.PP
.PD
emulator \[dq]MESS\[dq] dmess \[dq]mess\\mess.exe\[dq] \[dq]\[dq]
.PD 0
.PP
.PD
emulator \[dq]Raine\[dq] draine \[dq]raine\\raine.exe\[dq] \[dq]\[dq]
.PD 0
.PP
.PD
emulator \[dq]Custom Raine\[dq] draine \[dq]raine\\raine2.bat\[dq] \[dq]\[dq]
.PD 0
.PP
.PD
emulator \[dq]SNes9x\[dq] generic \[dq]c:\\game\\snes9x\\snes9x.exe\[dq] \[dq]%f\[dq]
.PD 0
.PP
.PD
emulator \[dq]ZSNes\[dq] generic \[dq]c:\\game\\zsnes\\zsnes.exe\[dq] \[dq]\-e \-m roms\\%f\[dq]
.PD 0
.PP
.PD
.RE
.PP
Examples for Linux and Mac OS X:
.PP
.RS 4
emulator \[dq]AdvanceMAME\[dq] advmame \[dq]advmame\[dq] \\
.PD 0
.PP
.PD
	\[dq]%o[,\-ror,\-flipx,\-rol] %o[,,\-flipy,]\[dq]
.PD 0
.PP
.PD
.RE
.SS emulator_roms/roms_filter/altss/flyers/cabinets/icons/titles 
Selects additional directories for the emulators. These
directories are used in addition to any other directory
defined in the emulator config file. The preview images and
sounds files are also searched also in any \`.zip\' file present
in these directories.
.PP
emulator_roms \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
emulator_roms_filter \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
emulator_altss \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
emulator_flyers \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
emulator_cabinets \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
emulator_marquees \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
emulator_icons \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
emulator_titles \[dq]EMULATOR\[dq] \[dq]LIST\[dq]
.PD 0
.PP
.PD
.PP
Commands:
.RS 4
.PD 0
.HP 4
.I roms
List of directories used for the roms. This
option is used only for the \`generic\' emulator
type. All the other emulators use the
emulator\-specific config file to set the rom
path.
.HP 4
.I roms_filter
List of pattern for the file to list.
An empty pattern means all files.
.HP 4
.I altss
Snapshot directory, used for snap images and
sounds. If possible, the directories
specified in the emulator configuration file
are also used.
.HP 4
.I flyers
Flyers directory.
.HP 4
.I cabinets
Cabinets directory.
.HP 4
.I marquees
Marquees directory.
.HP 4
.I icons
Icons directory.
.HP 4
.I titles
Titles directory.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR
The name for the emulator. Must be the same
name of a defined emulator
.HP 4
.I LIST
List of directories or patterns. In DOS and Windows
use the \`;\' char as separator. In Linux and
Mac OS X use the \`:\' char.
.PD
.RE
.PP
Examples for DOS and Windows:
.PP
.RS 4
emulator_roms \[dq]SNes9x\[dq] \[dq]c:\\game\\snes9x\\roms;c:\\game\\zsnes\\roms2\[dq]
.PD 0
.PP
.PD
emulator_roms_filter \[dq]SNes9x\[dq] \[dq]*.smc;*.sfc;*.fig;*.1\[dq]
.PD 0
.PP
.PD
emulator_flyers \[dq]SNes9x\[dq] \[dq]c:\\game\\zsnes\\fly\[dq]
.PD 0
.PP
.PD
emulator_cabinets \[dq]SNes9x\[dq] \[dq]c:\\game\\zsnes\\cab\[dq]
.PD 0
.PP
.PD
emulator_marquees \[dq]SNes9x\[dq] \[dq]c:\\game\\zsnes\\mar\[dq]
.PD 0
.PP
.PD
emulator_roms \[dq]ZSNes\[dq] \[dq]c:\\game\\zsnes\\roms\[dq]
.PD 0
.PP
.PD
emulator_roms_filter \[dq]ZSNes\[dq] \[dq]*.smc;*.sfc;*.fig;*.1\[dq]
.PD 0
.PP
.PD
.RE
.SS mode 
Selects the menu listing mode.
.PP
[EMULATOR/]mode full | full_mixed | text | list | list_mixed | tile_small
.PD 0
.PP
.PD
	| tile_normal | tile_big | tile_enormous | tile_giant
.PD 0
.PP
.PD
	| tile_icon | tile_marquee
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR/
Nothing for the default value, or an emulator
name for a specific emulator option.
.HP 4
.I full
Full screen preview.
.HP 4
.I full_mixed
Full screen preview with 4 images.
.HP 4
.I text
Game list.
.HP 4
.I list
Game list and preview of the selected game (default).
.HP 4
.I list_mixed
Game list and 4 preview of the selected game.
.HP 4
.I tile_small
Show the preview of 4x3 games.
.HP 4
.I tile_normal
Show the preview of 5x6 games.
.HP 4
.I tile_big
Show the preview of 8x6 games.
.HP 4
.I tile_enormous
Show the preview of 12x9 games.
.HP 4
.I tile_giant
Show the preview of 16x12 games.
.HP 4
.I tile_icon
Special mode for icon preview.
.HP 4
.I tile_marquee
Special mode for marquee preview.
.PD
.RE
.SS mode_skip 
Disables some menu modes when you press \`tab\'.
.PP
mode_skip (full | full_mixed | text | list | list_mixed
.PD 0
.PP
.PD
	| tile_small | tile_normal | tile_big | tile_enormous
.PD 0
.PP
.PD
	| tile_giant | tile_icon | tile_marquee)*
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I SKIP
Multiple selections of disabled modes. Use
an empty list to enable all the modes.
.PD
.RE
.PP
Examples:
.PP
.RS 4
mode_skip tile_giant
.PD 0
.PP
.PD
mode_skip full full_mixed list tile_small tile_giant
.PD 0
.PP
.PD
mode_skip
.PD 0
.PP
.PD
.RE
.SS sort 
Selects the sort order of the games displayed.
.PP
[EMULATOR/]sort parent | name | time | play | year | manufacturer
.PD 0
.PP
.PD
	| type | group | size | resolution | info
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR/
Nothing for the default value, or an emulator
name for a specific emulator option.
.HP 4
.I parent
Game parent name.
.HP 4
.I emulator
Emulator name.
.HP 4
.I name
Game name.
.HP 4
.I time
Total Time played.
.HP 4
.I play
Total Play times.
.HP 4
.I timeperplay
Time per play.
.HP 4
.I year
Game year release.
.HP 4
.I manufacturer
Game manufacturer.
.HP 4
.I type
Game type.
.HP 4
.I group
Game group.
.HP 4
.I size
Size of the game rom.
.HP 4
.I resolution
Resolution of the game display.
.HP 4
.I info
External information imported with the
\`info_import\' option.
.PD
.RE
.SS preview 
Selects the type of the images displayed.
.PP
[EMULATOR/]preview snap | titles | flyers | cabinets
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR/
Nothing for the default value, or an emulator
name for a specific emulator option.
.HP 4
.I snap
Files in the \`snap\' and \`altss\' dir.
.HP 4
.I flyers
Files in the \`flyers\' dir.
.HP 4
.I cabinets
Files in the \`cabinets\' dir.
.HP 4
.I titles
Files in the \`titles\' dir.
.PD
.RE
.PP
The \`icons\' and \`marquees\' images can be selected with the
special \`mode\' options \`tile_icon\' and \`tile_marquee\'.
.SS preview_expand 
Enlarges the screen area used by the vertical games on horizontal
tile (and horizontal games in vertical tile).
.PP
preview_expand FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Expansion float factor from 1.0 to 3.0
(default 1.15)
.PD
.RE
.PP
Examples:
.PP
.RS 4
preview_expand 1.15
.PD 0
.PP
.PD
.RE
.SS preview_default_* 
Selects the default images. When an image for the selected game
is not found, a default image can be displayed.
.PP
preview_default \[dq]FILE\[dq]
.PD 0
.PP
.PD
preview_default_snap \[dq]FILE\[dq]
.PD 0
.PP
.PD
preview_default_flyer \[dq]FILE\[dq]
.PD 0
.PP
.PD
preview_default_cabinet \[dq]FILE\[dq]
.PD 0
.PP
.PD
preview_default_icon \[dq]FILE\[dq]
.PD 0
.PP
.PD
preview_default_marquee \[dq]FILE\[dq]
.PD 0
.PP
.PD
preview_default_title \[dq]FILE\[dq]
.PD 0
.PP
.PD
.PP
Commands:
.RS 4
.PD 0
.HP 4
.I default
Selects the default image for all preview
modes.
.HP 4
.I default_TAG
Selects the default image for a single
preview mode.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FILE
The complete PATH of the image.
.PD
.RE
.PP
Examples:
.PP
.RS 4
preview_default \[dq]C:\\MAME\\DEFAULT.PNG\[dq]
.PD 0
.PP
.PD
preview_default_marquee \[dq]C:\\MAME\\DEFMAR.PNG\[dq]
.PD 0
.PP
.PD
preview_default_icon \[dq]C:\\MAME\\DEFICO.ICO\[dq]
.PD 0
.PP
.PD
.RE
.SS icon_space 
Selects the space size between icons. The \`icon\' mode is
available only if you set the option \`emulator_icons\' in the
emulator config file.
.PP
icon_space SPACE
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I SPACE
The number of pixel between icons (default 43).
.PD
.RE
.PP
In the icon display the game title is displayed in multiple rows
if there is enough space.
.SS merge 
Selects the expected format of your romset. It\'s used to test
the existence of the correct zips needed to run the games.
.PP
merge none | differential | parent | any | disable
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Every clone zip contains all the needed roms.
.HP 4
.I differential
Every clone zip contains only
the unique roms (default).
.HP 4
.I parent
All the roms are in the parent zip.
.HP 4
.I any
Any of the above, use this if you have
a rom set that is organized poorly.
.HP 4
.I disable
Check disabled.
.PD
.RE
.SS game 
Contains various information of the know games.
A \`game\' option is added automatically at the configuration
files for any rom found. It\'s used to keep some game
information like the play time.
.PP
game \[dq]EMULATOR/GAME\[dq] \[dq]GROUP\[dq] \[dq]TYPE\[dq] TIME PLAY \[dq]DESC\[dq]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR
Name of the emulator.
.HP 4
.I GAME
Short name of the game, generally the
rom name without the extension.
.HP 4
.I GROUP
Name of the group of the game or empty \[dq]\[dq].
.HP 4
.I TYPE
Name of the type of the game or empty \[dq]\[dq].
.HP 4
.I TIME
Time played in seconds.
.HP 4
.I PLAY
Number of play.
.HP 4
.I DESC
User description or empty \[dq]\[dq].
.PD
.RE
.PP
The GROUP, TYPE and DESC argument overwrite any
other value imported with the \`group_import\', \`type_import\',
and \`desc_import\' options. The imported values take effect
only if the user GROUP, TYPE and DESC are empty.
.PP
Examples:
.PP
.RS 4
game \[dq]advmame/puckman\[dq] \[dq]Very Good\[dq] \[dq]Arcade\[dq] \\
.PD 0
.PP
.PD
	1231 21 \[dq]Pac\-Man Japanese\[dq]
.PD 0
.PP
.PD
game \[dq]advmame/1943\[dq] \[dq]\[dq] \[dq]\[dq] 121 4 \[dq]1943 !!\[dq]
.PD 0
.PP
.PD
.RE
.SS Display Configuration Options 
This section describes the options used to customize the display.
.SS device_video_* 
These options are used to customize the video drivers.
.PP
All the \`device_video_*\' options defined in the \`advdev.txt\' file can
be used.
.PP
If you use a \`System\' video driver, you don\'t need to set these
options. They are mostly ignored.
.PP
With a \`Generate\' video drivers these options are used to select
and create the correct video mode. If missing the settings for a
standard Multisync SVGA monitor are used.
.SS display_size 
Selects the desired width of the video mode.
.PP
display_size WIDTH
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I WIDTH
Width in pixels of the video mode. The nearest
available video mode is chosen (default 1024).
.PD
.RE
.SS display_restoreatgame 
Selects whether to reset the video mode before running the
emulator.
.PP
[EMULATOR/]display_restoreatgame yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR/
Nothing for the default value, or an emulator
name for a specific emulator option.
.HP 4
.I yes
Reset the video mode (default).
.HP 4
.I no
Maintain the current graphics mode.
.PD
.RE
.SS display_restoreatexit 
Selects whether to reset the video mode before exiting.
.PP
display_restoreatexit yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Reset the video mode (default).
.HP 4
.I no
Maintain the current graphics mode.
.PD
.RE
.SS display_orientation 
Selects the desired orientation of the screen.
.PP
display_orientation (flip_xy | mirror_x | mirror_y)*
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I mirror_x
Mirror in the horizontal direction.
.HP 4
.I mirror_y
Mirror in the vertical direction.
.HP 4
.I flip_xy
Swap the x and y axes.
.PD
.RE
.PP
Examples:
.PP
.RS 4
display_orientation flip_xy mirror_x
.PD 0
.PP
.PD
.RE
.SS display_brightness 
Selects the image brightness factor.
.PP
display_brightness FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Brightness float factor (default 1.0).
.PD
.RE
.PP
Examples:
.PP
.RS 4
display_brightness 0.9
.PD 0
.PP
.PD
.RE
.SS display_gamma 
Selects the image gamma correction factor.
.PP
display_gamma FACTOR
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Gamma float factor (default 1.0).
.PD
.RE
.PP
Examples:
.PP
.RS 4
display_gamma 0.9
.PD 0
.PP
.PD
.RE
.SS Sound Configuration Options 
This section describes the options used to customize the sound.
.SS device_sound_* 
These options are used to customize the audio drivers.
.PP
All the \`device_sound_*\' options defined in the \`advdev.txt\' file can
be used.
.SS sound_volume 
Sets the global sound volume.
.PP
sound_volume VOLUME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I VOLUME
The volume attenuation in dB (default \-3).
The attenuation is a negative value from \-40 to 0.
.PD
.RE
.PP
Examples:
.PP
.RS 4
sound_volume \-5
.PD 0
.PP
.PD
.RE
.SS sound_latency 
Sets the audio latency.
.PP
sound_latency TIME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I TIME
Latency in seconds from 0.01 to 2.0.
(default 0.1)
.PD
.RE
.PP
Increase the value if your hear a choppy audio.
.SS sound_buffer 
Sets the size of the lookahead audio buffer for decoding.
.PP
sound_buffer TIME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I TIME
Buffer size in seconds from 0.05 to 2.0.
(default 0.1)
.PD
.RE
.PP
Increase the value if your hear a choppy audio.
.SS sound_foreground_EVENT 
Selects the sounds played in foreground for the various events.
.PP
sound_foreground_begin none | default | FILE
.PD 0
.PP
.PD
sound_foreground_end none | default | FILE
.PD 0
.PP
.PD
sound_foreground_key none | default | FILE
.PD 0
.PP
.PD
sound_foreground_start none | default | FILE
.PD 0
.PP
.PD
sound_foreground_stop none | default | FILE
.PD 0
.PP
.PD
.PP
Commands:
.RS 4
.PD 0
.HP 4
.I begin
Sound played at AdvanceMENU startup.
.HP 4
.I end
Sound played at AdvanceMENU exit.
.HP 4
.I start
Sound played at emulator startup.
.HP 4
.I stop
Sound played at emulator exit.
.HP 4
.I key
Sound played when a key is pressed.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No sound.
.HP 4
.I default
Use the default sound.
.HP 4
.I FILE
Path of the sound file (.wav or .mp3).
.PD
.RE
.SS sound_background_EVENT 
Selects the sounds played in background for the various events.
.PP
sound_background_begin none | FILE
.PD 0
.PP
.PD
sound_background_end none | FILE
.PD 0
.PP
.PD
sound_background_start none | FILE
.PD 0
.PP
.PD
sound_background_stop none | FILE
.PD 0
.PP
.PD
sound_background_loop none | default | FILE
.PD 0
.PP
.PD
.PP
Commands:
.RS 4
.PD 0
.HP 4
.I begin
Sound played at AdvanceMENU startup.
.HP 4
.I end
Sound played at AdvanceMENU exit.
.HP 4
.I start
Sound played at emulator startup.
.HP 4
.I stop
Sound played at emulator exit.
.HP 4
.I loop
Sound played in loop if no other background
sound is available.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No sound
.HP 4
.I default
Use the default sound
.HP 4
.I FILE
Path of the sound file (.wav or .mp3)
.PD
.RE
.SS sound_background_loop_dir 
Selects the background music directory to search for MP3 and WAV
files. Music tracks will be played in random order.
.PP
Multiple directories may be specified by separating each with a
semicolon \`;\' in DOS and Windows, with a double\-colon \`:\' in Linux
and Mac OS X.
.PP
Note that this directory must be used only for your music.
The emulated game recordings, played when the cursor is moved on
the game, are stored in the snap directory defined in the emulator
configuration file or with the \`emulator_altss\' option.
.PP
sound_background_loop_dir \[dq]DIR\[dq]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I DIR
Directory for .mp3 and .wav files.
.PD
.RE
.PP
Examples:
.PP
.RS 4
sound_background_loop_dir C:\\MP3\\POP;C:\\MP3\\ROCK
.PD 0
.PP
.PD
.RE
.SS Input Configuration Options 
This section describes the options used to customize the user
input.
.SS device_keyboard/joystick/mouse 
These options are used to customize the input drivers.
.PP
All the \`device_keyboard/joystick/mouse_*\' options defined in
the \`advdev.txt\' file can be used.
.PP
As default the mouse and the joystick support is disabled.
To enable it you must add the options:
.PP
.RS 4
device_mouse auto
.PD 0
.PP
.PD
device_joystick auto
.PD 0
.PP
.PD
.RE
.PP
in your advmenu.rc file.
.SS mouse_delta 
Selects the mouse/trackball sensitivity. Increase the value for
a slower movement. Decrease it for a faster movement.
.PP
mouse_delta STEP
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I STEP
Mouse/trackball position step (default 100).
.PD
.RE
.SS User Interface 
This section describes the options used to customize the user
interface.
.SS ui_font 
Selects a font file. The formats TrueType (TTF), GRX, PSF and
RAW are supported. You can find a collection of fonts in the
\`contrib\' directory.
.PP
ui_font auto | \[dq]FILE\[dq]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Use the built\-in font (default).
.HP 4
.I FILE
Font file path.
.PD
.RE
.PP
The TrueType (TTF) format is supported only if the program is
compiled with the FreeType2 library.
.SS ui_fontsize 
Selects the font size, if the specified font is scalable.
The size is expressed in number of rows and columns of text in the
screen.
.PP
ui_fontsize auto | ROWS [COLS]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I auto
Automatically compute the size (default).
.HP 4
.I ROWS
Number of text rows.
.HP 4
.I COLS
Number of text columns. If omitted is computed from
the number of rows.
.PD
.RE
.SS ui_background 
Defines a background image in .PNG or MNG format. The image is
stretched to fit the screen.
.PP
ui_background FILE | none
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No image (default).
.HP 4
.I FILE
File in .PNG or .MNG format to load.
.PD
.RE
.PP
For .MNG files only the first frame is used.
.SS ui_exit 
Defines an exit image/clip in .PNG or .MNG format displayed
at the frontexit exit. The image is stretched to fit the screen.
.PP
ui_exit FILE | none
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No image (default).
.HP 4
.I FILE
File in .PNG or .MNG format to load.
.PD
.RE
.SS ui_startup 
Defines a startup image/clip in .PNG or .MNG format displayed
at the frontend startup. The image is stretched to fit the screen.
.PP
ui_startup FILE | none
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No image (default).
.HP 4
.I FILE
File in .PNG or .MNG format to load.
.PD
.RE
.SS ui_help 
Defines an help image/clip in .PNG or .MNG format displayed when the
user press F1. The image is stretched to fit the screen.
.PP
ui_help FILE | none
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No image (default).
.HP 4
.I FILE
File in .PNG or .MNG format to load.
.PD
.RE
.SS ui_gamemsg 
One line message displayed when a game is chosen. The
message is displayed only if the option \`display_restoreatgame\' is
set to \`no\'.
.PP
ui_gamemsg \[dq]MESSAGE\[dq]
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I MESSAGE
Message to display (default \[dq]Run Game\[dq]).
To prevent the display of the message use the
empty string \[dq]\[dq].
.PD
.RE
.PP
Examples:
.PP
.RS 4
ui_gamemsg \[dq]Avvio il gioco...\[dq]
.PD 0
.PP
.PD
.RE
.SS ui_game 
Selects the preview type to display when a game is run. The
preview is displayed only if the option \`display_restoreatgame\' is
set to \`no\'.
.PP
ui_game none | snap | flyers | cabinets | titles
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Don\'t display any preview.
.HP 4
.I snap, flyers, cabinets, titles
Display the
specified preview. (default snap).
.PD
.RE
.SS ui_skiptop/bottom/left/right 
Defines the border area of the screen not used by the menu.
Generally it\'s the part of the screen used by the background image.
If a \`ui_background\' image is specified these values refer at image
size before stretching, otherwise they refer at the current video
mode size.
.PP
ui_skiptop N
ui_skipbottom N
ui_skipleft N
ui_skipright N
.PP
Options:
.RS 4
.PD 0
.HP 4
.I N
Number of pixel to skip (default 0).
.PD
.RE
.SS ui_topbar/bottombar 
Enables or disables the top and bottom information bars.
.PP
ui_topbar yes | no
ui_bottombar yes | no
.SS ui_color 
Selects the user interface colors.
.PP
ui_color TAG FOREGROUND BACKGROUND
.PD 0
.PP
.PD
.PP
Tags:
.RS 4
.PD 0
.HP 4
.I help
Help.
.HP 4
.I help_tag
Help highlight.
.HP 4
.I submenu_bar
Submenu title.
.HP 4
.I submenu_item
Submenu entry.
.HP 4
.I submenu_item_select
Submenu selected entry.
.HP 4
.I submenu_hidden
Submenu hidden entry.
.HP 4
.I submenu_hidden_select
Submenu selected hidden entry.
.HP 4
.I menu_item
Menu entry.
.HP 4
.I menu_hidden
Menu hidden entry.
.HP 4
.I menu_tag
Menu highlight entry.
.HP 4
.I menu_item_select
Menu selected entry.
.HP 4
.I menu_hidden_select
Menu hidden selected entry.
.HP 4
.I menu_tag_select
Menu selected highlight.
.HP 4
.I bar
Title.
.HP 4
.I bar_tag
Title highlight.
.HP 4
.I bar_hidden
Title hidden text.
.HP 4
.I grid
Scrollbar marker and generic background color.
.HP 4
.I backdrop
Backdrop outline and missing backdrop.
.HP 4
.I icon
Icon outline and missing icon.
.HP 4
.I cursor
Flashing cursor.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FOREGROUND
Foreground color in RRGGBB
hex format. For example FF0000 is red,
00FF00 is green and 0000FF is blue.
.HP 4
.I BACKGROUND
Background color. Like foreground color.
.PD
.RE
.SS ui_clip 
Selects how play the video clips.
.PP
ui_clip none | single | singleloop | multi | multiloop | multiloopall
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
No clip.
.HP 4
.I single
Play only one clip and only one time (default).
.HP 4
.I singleloop
Play only one clip continuously. The sound is
not looped.
.HP 4
.I multi
Play all the clips.
.HP 4
.I multiloop
Play all the clips, and loop the clip on the
cursor. The sound is not looped.
.HP 4
.I multiloopall
Play all the clips, and loop all the clips.
The sound is not looped.
.PD
.RE
.SS ui_translucency 
Selects the translucency of the user interface.
.PP
ui_translucency FACTOR
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FACTOR
Translucency factor from 0 to 1
(default 0.6).
.PD
.RE
.PP
The translucency has effect only if you have a background
image.
.SS ui_command 
Defines the user commands. These commands are executed as
shell scripts. The video mode is not changed, so they must be
silent.
.PP
ui_command \[dq]MENU\[dq] SCRIPT
.PP
Options:
.RS 4
.PD 0
.HP 4
.I MENU
Name of the menu entry.
.HP 4
.I SCRIPT
Commands to execute. If you need to insert more
command rows you can end the line with the \\ char.
.PD
.RE
.PP
In the script text some macro are substituted with information of
the selected game:
.RS 4
.PD 0
.HP 4
.I %s
The game name. For example \[dq]pacman\[dq].
.HP 4
.I %p
The complete path of the rom. For
example \[dq]c:\\emu\\roms\\pacman.zip\[dq].
.HP 4
.I %f
The rom name with the extension. For
example \[dq]pacman.zip\[dq].
.PD
.RE
.PP
If no game is selected the macros aren\'t substituted.
.PP
If the script exits with an error code, a message is displayed.
.PP
Examples:
.PP
.RS 4
ui_command \[dq]Delete Hiscore\[dq] \\
.PD 0
.PP
.PD
	rm ~/.advance/hi/%s.hi
.PD 0
.PP
.PD
ui_command \[dq]Enable GamePad\[dq] \\
.PD 0
.PP
.PD
	rmmod analog \\
.PD 0
.PP
.PD
	sleep 1 \\
.PD 0
.PP
.PD
	modprobe analog js=gamepad
.PD 0
.PP
.PD
.RE
.SS ui_command_menu 
Selects the name of the menu entry for the commands submenu.
.PP
ui_command_menu MENU
.PP
Options:
.RS 4
.PD 0
.HP 4
.I MENU
Name of the menu entry (default \[dq]Command\[dq]).
.PD
.RE
.SS ui_command_error 
Selects the message to display if a command fails.
.PP
ui_command_error MSG
.PP
Options:
.RS 4
.PD 0
.HP 4
.I MSG
Message to display (default \[dq]Error running the command\[dq]).
.PD
.RE
.SS ui_menukey 
Enables or disables the key names in the menu entries.
.PP
ui_menukey yes | no
.SS ui_console 
Changes the user interface behavior for the use on a game
console system. Mainly for AdvanceCD.
.PP
ui_console yes | no
.PP
In console mode the menu is reduced to contains only the
minimal commands, and the sound volume is propagated to the
emulators if possible.
.SS Input Configuration Options 
This section describes the options used to customize the user
input.
.SS device_keyboard/joystick/mouse_* 
These options are used to customize the input drivers.
.PP
All the \`device_keyboard/joystick/mouse_*\' options defined in
the \`advdev.txt\' file can be used.
.SS input_hotkey 
Enables or disables the recognition of the special OS keyboard
sequences.
.PP
input_hotkey yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I no
No hot key recognition.
.HP 4
.I yes
Hot key recognition (default).
.PD
.RE
.PP
In DOS the hotkey recognized are:
.RS 4
.PD 0
.HP 4
.I CTRL+ALT+DEL
Reset.
.HP 4
.I CTRL+ALT+END
Quit.
.HP 4
.I CTRL+BREAK (Pause)
Break.
.PD
.RE
.PP
In Linux the hotkey recognized generally are:
.RS 4
.PD 0
.HP 4
.I CTRL+C
Break.
.HP 4
.I ALT+Fx
Change virtual console.
.PD
.RE
.SS lock 
Locks or unlocks the user interface. When locked, the user can
only browse and run games. Options can\'t be changed and the user
cannot exit.
.PP
lock yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Locked mode activate.
.HP 4
.I no
Locked mode deactivate (default).
.PD
.RE
.SS event_assign 
Customizes the input keyboard codes that trigger menu
events.
.PP
event_assign EVENT EXPRESSION
.PD 0
.PP
.PD
.PP
Events:
.RS 4
.PD 0
.HP 4
.I up, down, left, right
Movement.
.HP 4
.I home, end, pgup, pgdn
Movement.
.HP 4
.I enter
Main action, start.
.HP 4
.I esc
Back action, exit & cancel.
.HP 4
.I space
Change action, select & deselect.
.HP 4
.I ins
Select all.
.HP 4
.I del
Deselect all.
.HP 4
.I menu
The main menu.
.HP 4
.I sort
Changes the sort mode.
.HP 4
.I mode
Change the display mode.
.HP 4
.I preview
Change the preview mode.
.HP 4
.I emulator
The emulator menu.
.HP 4
.I help
Show a little help.
.HP 4
.I group
Select a game group.
.HP 4
.I type
Select a game type.
.HP 4
.I exclude
Exclude some games with filters.
.HP 4
.I setgroup
Select the group of the current game
.HP 4
.I settype
Select the type of the current game
.HP 4
.I runclone
Run a game clone.
.HP 4
.I shutdown
Shutdown the machine.
.HP 4
.I command
The file command menu.
.HP 4
.I rotate
Rotate the screen of 90°.
.HP 4
.I lock
Lock/unlock the user interface.
.HP 4
.I mute
Mute/unmute the audio.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EXPRESSION
Definition of the key expression that
generates the event. It\'s a combination of
the key names or scan\-code, and of the operators
\`not\', \`or\'. The \`and\' operator is implicit
between consecutive scan\-codes.
.HP 4
.I KEY
The available key names are:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r,
s, t, u, v, w, x, y, z, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
0_pad, 1_pad, 2_pad, 3_pad, 4_pad, 5_pad, 6_pad,
7_pad, 8_pad, 9_pad, f1, f2, f3, f4, f5, f6, f7, f8,
f9, f10, f11, f12, esc, backquote, minus, equals,
backspace, tab, openbrace, closebrace, enter,
semicolon, quote, backslash, less, comma, period,
slash, space, insert, del, home, end, pgup, pgdn, left,
right, up, down, slash_pad, asterisk_pad, minus_pad,
plus_pad, period_pad, enter_pad, prtscr, pause,
lshift, rshift, lcontrol, rcontrol, lalt, ralt,
lwin, rwin, menu, scrlock, numlock, capslock.
.PD
.RE
.PP
Examples:
.PP
.RS 4
event_assign enter lcontrol or enter
.PD 0
.PP
.PD
event_assign menu 90 or 35
.PD 0
.PP
.PD
event_assign emulator 91 23 or not 21 33
.PD 0
.PP
.PD
.RE
.PP
You can use the utility \`advk\' to get the key scancodes and
names.
.SS event_repeat 
Selects the repeat rate of the various events.
.PP
event_repeat FIRST_TIME NEXT_TIME
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I FIRST_TIME
Time of the first repeat in ms.
.HP 4
.I NEXT_TIME
Time of the next repeats in ms.
.PD
.RE
.SS event_mode 
Selects whether to wait for a complete screen update before
processing the next event.
.PP
event_mode wait | fast
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I wait
The screen is completely redrawn before processing
the next event.
.HP 4
.I fast
If an event is waiting, the screen drawing
is interrupted (default).
.PD
.RE
.SS event_alpha 
Disables the alphanumeric keys for fast moving.
If you have a keyboard encoder or a keyboard hack with some
buttons remapped to alphanumeric keys, it\'s useful to disable
them.
.PP
event_alpha yes | no
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I yes
Enable (default).
.HP 4
.I no
Disable.
.PD
.RE
.SS Other Configuration Options 
.SS idle_start 
Automatically starts a random game after some time of inactivity.
You can also configure the AdvanceMAME option \`input_idleexit\'
in the file \`advmame.rc\' to create a continuous demo mode.
.PP
idle_start START_TIMEOUT REPEAT_TIMEOUT
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I START_TIMEOUT
Number of seconds to wait for the
first run. 0 means never (default never).
.HP 4
.I REPEAT_TIMEOUT
Number of seconds to wait for the
next run. 0 means never (default never).
.PD
.RE
.PP
Examples:
.PP
.RS 4
idle_start 400 60
.PD 0
.PP
.PD
.RE
.SS idle_screensaver 
Selects the start time of the default screen saver. The screensaver
is a slide show of the available snapshots.
.PP
idle_screensaver START_TIMEOUT REPEAT_TIMEOUT
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I START_TIMEOUT
Number of seconds to wait for the
first run. 0 means never (default 60).
.HP 4
.I REPEAT_TIMEOUT
Number of seconds to wait for the
next run. 0 means never (default 10).
.PD
.RE
.PP
Examples:
.PP
.RS 4
idle_screensaver 40 5
.PD 0
.PP
.PD
.RE
.SS idle_screensaver_preview 
Selects the preview type to use in the screensaver. Like
the preview option.
.PP
idle_screensaver_preview none | exit | shutdown | play
.PD 0
.PP
.PD
	| snap | flyers | cabinets | titles
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Shutdown the monitor using the VESA/PM services
if available. Otherwise use a black image.
.HP 4
.I exit
Exit from the application.
.HP 4
.I shutdown
Shutdown the machine.
.HP 4
.I snap, flyers, cabinets, titles
Start a mute slide show
of the specified image type (default snap).
.HP 4
.I play
Start a snap slide show using the animated
snapshots and the game sounds. The static
snapshots are ignored.
.PD
.RE
.SS group/type 
Selects the available \`group\' and \`type\' category names and
which of them to show.
.PP
group \[dq]STRING\[dq]
.PD 0
.PP
.PD
type \[dq]STRING\[dq]
.PD 0
.PP
.PD
[EMULATOR/]group_include \[dq]STRING\[dq]
.PD 0
.PP
.PD
[EMULATOR/]type_include \[dq]STRING\[dq]
.PD 0
.PP
.PD
.PP
Commands:
.RS 4
.PD 0
.HP 4
.I group, type
Define a category.
.HP 4
.I group_include, type_include
Show a category.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I EMULATOR/
Nothing for the default value, or an emulator
name for a specific emulator option.
.HP 4
.I STRING
name of the category
.PD
.RE
.SS group/type/desc/info_import 
Selects the automatic import of the groups, types, descriptions
and extra information from an external file. The extra info are
additional information displayed for every game.
.PP
The file formats supported are CATVER, CATLIST/CAT32, MacMAME and NMS.
The files are read in the current directory in DOS and Windows
and in the $home directory in Linux and Mac OS X.
.PP
WARNING! These options DON\'T OVERRIDE any user explicit
choices made with the \`game\' option.
.PP
desc_import (catver | mac | nms) \[dq]EMULATOR\[dq] \[dq]FILE\[dq] [\[dq]SECTION\[dq]]
.PD 0
.PP
.PD
info_import (catver | mac | nms) \[dq]EMULATOR\[dq] \[dq]FILE\[dq] [\[dq]SECTION\[dq]]
.PD 0
.PP
.PD
group_import (catver | mac | nms) \[dq]EMULATOR\[dq] \[dq]FILE\[dq] [\[dq]SECTION\[dq]]
.PD 0
.PP
.PD
type_import (catver | mac | nms) \[dq]EMULATOR\[dq] \[dq]FILE\[dq] [\[dq]SECTION\[dq]]
.PD 0
.PP
.PD
.PP
Commands:
.RS 4
.PD 0
.HP 4
.I desc_import
Imports the game names shown in the menu.
.HP 4
.I info_import
Imports additional information printed on
bottom bar of the menu.
.HP 4
.I group_import
Imports the group names of the game.
.HP 4
.I type_import
Imports the type names of the game.
.PD
.RE
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Don\'t import.
.HP 4
.I catver
Import in the CATVER format. In this format you must
also specify the section to load.
.HP 4
.I catlist
Import in the CATLIST/CAT32 format.
.HP 4
.I mac
Import in the MacMAME format.
.HP 4
.I nms
Import in the NMS format.
.HP 4
.I EMULATOR
The emulator tag name as specified in
the \`emulator\' option.
.HP 4
.I FILE
The file name.
.HP 4
.I SECTION
The section name (only for the \`ini\' format).
.PD
.RE
.PP
Examples:
.PP
.RS 4
group_import catver \[dq]advmame\[dq] \[dq]catver.ini\[dq] \[dq]Category\[dq]
.PD 0
.PP
.PD
info_import catver \[dq]advmame\[dq] \[dq]catver.ini\[dq] \[dq]VerAdded\[dq]
.PD 0
.PP
.PD
group_import catlist \[dq]advmame\[dq] \[dq]catlist.ini\[dq]
.PD 0
.PP
.PD
type_import mac \[dq]advmame\[dq] \[dq]Genre 37b14.txt\[dq]
.PD 0
.PP
.PD
desc_import nms \[dq]raine\[dq] \[dq]raine.nms\[dq]
.PD 0
.PP
.PD
.RE
.PP
The CATVER/CATLIST files can be downloaded at:
.PP
.RS 4
http://www.progettoemma.net/?catlist
.PD 0
.PP
.PD
.RE
.SS misc_exit 
Selects the exit mode.
.PP
misc_exit none | normal | shutdown | all
.PD 0
.PP
.PD
.PP
Options:
.RS 4
.PD 0
.HP 4
.I none
Exit is disabled.
.HP 4
.I normal
Exit is possible pressing ESC.
.HP 4
.I shutdown
Exit is possible pressing CTRL\-ESC.
.HP 4
.I all
All the exit modes are possible.
.PD
.RE
.SS misc_quiet 
Disables the copyright text message at the startup.
.PP
misc_quiet yes | no
.PD 0
.PP
.PD
.SH FORMATS SUPPORTED 
This is the list of the file formats supported by AdvanceMENU.
.PP
Images:
.RS 4
.PD 0
.HP 4
.I PNG
The PNG format.
.HP 4
.I PCX
The PCX format.
.HP 4
.I ICO
The ICON format.
.PD
.RE
.PP
Clips:
.RS 4
.PD 0
.HP 4
.I MNG
The MNG\-VLC (Very Low Complexity) sub format
without transparency and alpha channel.
Or the sub\-formats generated by AdvanceMAME or
by the \`advmng\' compression utility.
.PD
.RE
.PP
Sounds:
.RS 4
.PD 0
.HP 4
.I MP3
The MP3 format.
.HP 4
.I WAV
The WAV format with a sample size of 16 bit.
.PD
.RE
.PP
Fonts:
.RS 4
.PD 0
.HP 4
.I TTF
The TrueType format (with the FreeType2 library).
.HP 4
.I RAW
The RAW format.
.HP 4
.I PSF
The PSF format.
.HP 4
.I GRX
The GRX format.
.PD
.RE
.PP
Archives:
.RS 4
.PD 0
.HP 4
.I ZIP
The ZIP format.
.PD
.RE
.SH SIGNALS 
The program intercepts the following signals:
.RS 4
.PD 0
.HP 4
.I SIGQUIT
Exit normally.
.HP 4
.I SIGTERM, SIGINT, SIGALRM
Exit restoring only the output devices.
.HP 4
.I SIGHUP
Restart the program.
.PD
.RE
.SH COPYRIGHT 
This file is Copyright (C) 2003, 2004, 2005, 2012 Andrea Mazzoleni, Randy Schnedler.
